erreduarte
*** Found local files:
***   * /home/erreduarte/airflow/logs/dag_id=ELT_WB/run_id=manual__2024-09-27T18:10:33.034692+00:00/task_id=transform_WB_data/attempt=1.log
[2024-09-27T19:10:42.902+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T19:10:42.948+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT_WB.transform_WB_data manual__2024-09-27T18:10:33.034692+00:00 [queued]>
[2024-09-27T19:10:42.962+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT_WB.transform_WB_data manual__2024-09-27T18:10:33.034692+00:00 [queued]>
[2024-09-27T19:10:42.963+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-27T19:10:42.985+0100] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): transform_WB_data> on 2024-09-27 18:10:33.034692+00:00
[2024-09-27T19:10:42.991+0100] {standard_task_runner.py:72} INFO - Started process 1199047 to run task
[2024-09-27T19:10:42.993+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ELT_WB', 'transform_WB_data', 'manual__2024-09-27T18:10:33.034692+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/DAG_ELT_WB.py', '--cfg-path', '/tmp/tmpvol_31s4']
[2024-09-27T19:10:42.995+0100] {standard_task_runner.py:105} INFO - Job 290: Subtask transform_WB_data
[2024-09-27T19:10:43.167+0100] {task_command.py:467} INFO - Running <TaskInstance: ELT_WB.transform_WB_data manual__2024-09-27T18:10:33.034692+00:00 [running]> on host erreduarte
[2024-09-27T19:10:43.432+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='renanduarte' AIRFLOW_CTX_DAG_ID='ELT_WB' AIRFLOW_CTX_TASK_ID='transform_WB_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T18:10:33.034692+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T18:10:33.034692+00:00'
[2024-09-27T19:10:43.433+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T19:10:43.484+0100] {base.py:84} INFO - Retrieving connection 'azure_blob_storage'
[2024-09-27T19:10:45.704+0100] {logging_mixin.py:190} WARNING - /home/erreduarte/airflow/dags/DAG_ELT_WB.py:79 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-27T19:10:45.733+0100] {logging_mixin.py:190} WARNING - /home/erreduarte/airflow/dags/DAG_ELT_WB.py:80 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-27T19:10:45.741+0100] {logging_mixin.py:190} WARNING - /home/erreduarte/airflow/dags/DAG_ELT_WB.py:81 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-27T19:10:45.748+0100] {logging_mixin.py:190} WARNING - /home/erreduarte/airflow/dags/DAG_ELT_WB.py:82 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-27T19:10:45.756+0100] {logging_mixin.py:190} WARNING - /home/erreduarte/airflow/dags/DAG_ELT_WB.py:83 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-27T19:10:46.036+0100] {logging_mixin.py:190} WARNING - /home/erreduarte/airflow/dags/DAG_ELT_WB.py:86 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-27T19:10:46.043+0100] {logging_mixin.py:190} WARNING - /home/erreduarte/airflow/dags/DAG_ELT_WB.py:87 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-09-27T19:10:46.862+0100] {python.py:240} INFO - Done. Returned value was: ('Data successfully transformed. Saved in blob storage as rfd-container/WB_Data_Loans__Silver.csv',)
[2024-09-27T19:10:46.974+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T19:10:46.974+0100] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ELT_WB, task_id=transform_WB_data, run_id=manual__2024-09-27T18:10:33.034692+00:00, execution_date=20240927T181033, start_date=20240927T181042, end_date=20240927T181046
[2024-09-27T19:10:47.018+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-27T19:10:47.098+0100] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-27T19:10:47.109+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
