erreduarte
*** Found local files:
***   * /home/erreduarte/airflow/logs/dag_id=ELT_WB/run_id=manual__2024-09-27T18:10:33.034692+00:00/task_id=populate_dbo_WB_Loans/attempt=2.log
[2024-09-27T19:13:18.424+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T19:13:18.466+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT_WB.populate_dbo_WB_Loans manual__2024-09-27T18:10:33.034692+00:00 [queued]>
[2024-09-27T19:13:18.480+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT_WB.populate_dbo_WB_Loans manual__2024-09-27T18:10:33.034692+00:00 [queued]>
[2024-09-27T19:13:18.481+0100] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-27T19:13:18.509+0100] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): populate_dbo_WB_Loans> on 2024-09-27 18:10:33.034692+00:00
[2024-09-27T19:13:18.515+0100] {standard_task_runner.py:72} INFO - Started process 1199488 to run task
[2024-09-27T19:13:18.519+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ELT_WB', 'populate_dbo_WB_Loans', 'manual__2024-09-27T18:10:33.034692+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/DAG_ELT_WB.py', '--cfg-path', '/tmp/tmpwptjmnnn']
[2024-09-27T19:13:18.521+0100] {standard_task_runner.py:105} INFO - Job 298: Subtask populate_dbo_WB_Loans
[2024-09-27T19:13:18.700+0100] {task_command.py:467} INFO - Running <TaskInstance: ELT_WB.populate_dbo_WB_Loans manual__2024-09-27T18:10:33.034692+00:00 [running]> on host erreduarte
[2024-09-27T19:13:18.962+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='renanduarte' AIRFLOW_CTX_DAG_ID='ELT_WB' AIRFLOW_CTX_TASK_ID='populate_dbo_WB_Loans' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T18:10:33.034692+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T18:10:33.034692+00:00'
[2024-09-27T19:13:18.963+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T19:13:19.012+0100] {base.py:84} INFO - Retrieving connection 'microsoft_azure_database'
[2024-09-27T19:13:19.507+0100] {sql.py:531} INFO - Running statement: 
                BULK INSERT dbo.WB_Loans
                FROM 'WB_Data_Loans__Silver.csv'
                WITH (
                    DATA_SOURCE     = 'WorldBankData',
                    ROWTERMINATOR   = '0x0a',
                    FIELDTERMINATOR = ',',
                    FIRSTROW        = 2
                );
            , parameters: None
[2024-09-27T19:13:20.084+0100] {sql.py:540} INFO - Rows affected: 50000
[2024-09-27T19:13:20.174+0100] {logging_mixin.py:190} INFO - Table sucessfully populated
[2024-09-27T19:13:20.624+0100] {sql.py:531} INFO - Running statement: SELECT COUNT (*) FROM dbo.WB_Loans, parameters: None
[2024-09-27T19:13:20.768+0100] {python.py:240} INFO - Done. Returned value was: The table was created and contains 50000 rows
[2024-09-27T19:13:20.886+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T19:13:20.886+0100] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ELT_WB, task_id=populate_dbo_WB_Loans, run_id=manual__2024-09-27T18:10:33.034692+00:00, execution_date=20240927T181033, start_date=20240927T181318, end_date=20240927T181320
[2024-09-27T19:13:20.946+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-27T19:13:21.009+0100] {taskinstance.py:3900} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-09-27T19:13:21.012+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
